# This is a GitHub App Manifest. These settings will be used by default when
# initially configuring your GitHub App.
#
# NOTE: changing this file will not update your GitHub App settings.
# You must visit github.com/settings/apps/your-app-name to edit them.
#
# Read more about configuring your GitHub App:
# https://probot.github.io/docs/development/#configuring-a-github-app
#
# Read more about GitHub App Manifests:
# https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/

# The list of events the GitHub App subscribes to.
default_events:
- issue_comment
- issues
- pull_request
- pull_request_review
- pull_request_review_comment

default_permissions:
  issues: write
  metadata: read
  pull_requests: write
  single_file: read

single_file_name: .github/stale.yml

# The name of the GitHub App. Defaults to the name specified in package.json
name:

# The homepage of your GitHub App.
url:

# A description of the GitHub App.
description:

# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app.
# Default: true
public: false

